name: Deploy webapp to App Engine

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
        working-directory: src/web

      - name: Build
        run: npm run build:ci:gh
        working-directory: src/web

      # - name: Test
      #   run: npm run test:ci:gh
      #   working-directory: src/web

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: src/web/www

      # - name: Archive code coverage result
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: deploy_coverage
      #     path: src/web/coverage

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # BRANCH: gh-pages
          # FOLDER: deploy_dist
          folder: deploy_dist

      # # Deploy to App Engine
      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      #     service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      # - id: 'deploy'
      #   uses: 'google-github-actions/deploy-appengine@v2'

      # # Example of using the output
      # - id: 'test'
      #   run: 'curl "${{ steps.deploy.outputs.version_url }}"'